# Site title and subtitle. This is used in _includes/header.html
title: 'UserJoy Documentation'
subtitle: ''

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/userjoyco/documentation'

# Default categories (in order) to appear in the navigation
sections: [
    ['introduction', 'Introduction'],
    ['tracking', 'Tracking'],
    ['methods', 'Methods'],
    ['segmentation', 'Segmenting'],
    ['messaging', 'Messaging']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
# highlighter: 'coderay'

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: kramdown
kramdown:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
    use_coderay: true
    coderay:
        coderay_line_numbers: nil
        coderay_css: style
